## Задача 1.

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [4]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [5]:
mean_a = a.mean(axis=0)

In [6]:
print(mean_a)

[2.  8.4]


## Задача 2.

In [7]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


## Задача 3.

In [19]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1]) / (a_centered.shape[0] - 1)
a_centered_sp

2.0

## Задача 4.

In [21]:
a_cov = np.cov(a.T)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [22]:
cov = a_cov[0, 1]
cov

2.0